// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using senai.hroads.webAPI.Contexts;

namespace senai.hroads.webAPI.Migrations
{
    [DbContext(typeof(HroadsContext))]
    partial class HroadsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("senai.hroads.webAPI.Domains.ClasseDomain", b =>
                {
                    b.Property<int>("idClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nomeClasse")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idClasse");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            idClasse = 1,
                            nomeClasse = "Bárbaro"
                        },
                        new
                        {
                            idClasse = 2,
                            nomeClasse = "Cruzado"
                        },
                        new
                        {
                            idClasse = 3,
                            nomeClasse = "Caçadora de Demônios"
                        },
                        new
                        {
                            idClasse = 4,
                            nomeClasse = "Monge"
                        },
                        new
                        {
                            idClasse = 5,
                            nomeClasse = "Necromancer"
                        },
                        new
                        {
                            idClasse = 6,
                            nomeClasse = "Feiticeiro"
                        },
                        new
                        {
                            idClasse = 7,
                            nomeClasse = "Arcanista"
                        });
                });

            modelBuilder.Entity("senai.hroads.webAPI.Domains.ClasseHabilidadeDomain", b =>
                {
                    b.Property<int>("idClasseHabilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("idClasse")
                        .HasColumnType("int");

                    b.Property<int?>("idHabilidade")
                        .HasColumnType("int");

                    b.HasKey("idClasseHabilidade");

                    b.HasIndex("idClasse");

                    b.HasIndex("idHabilidade");

                    b.ToTable("ClasseHabilidades");
                });

            modelBuilder.Entity("senai.hroads.webAPI.Domains.HabilidadeDomain", b =>
                {
                    b.Property<int>("idHabilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("idTipoHabilidade")
                        .HasColumnType("int");

                    b.Property<string>("nomeHabilidade")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idHabilidade");

                    b.HasIndex("idTipoHabilidade");

                    b.ToTable("Habilidades");

                    b.HasData(
                        new
                        {
                            idHabilidade = 1,
                            idTipoHabilidade = 1,
                            nomeHabilidade = "Lança Mortal"
                        },
                        new
                        {
                            idHabilidade = 2,
                            idTipoHabilidade = 2,
                            nomeHabilidade = "Escudo Supremo"
                        },
                        new
                        {
                            idHabilidade = 3,
                            idTipoHabilidade = 3,
                            nomeHabilidade = "Recuperar Vida"
                        });
                });

            modelBuilder.Entity("senai.hroads.webAPI.Domains.PersonagemDomain", b =>
                {
                    b.Property<int>("idPersonagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("UsuarioDomainidUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("DATE");

                    b.Property<int>("idClasse")
                        .HasColumnType("int");

                    b.Property<int>("maxMana")
                        .HasColumnType("int");

                    b.Property<int>("maxVida")
                        .HasColumnType("int");

                    b.Property<string>("nomePersonagem")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idPersonagem");

                    b.HasIndex("UsuarioDomainidUsuario");

                    b.HasIndex("idClasse");

                    b.ToTable("Personagens");

                    b.HasData(
                        new
                        {
                            idPersonagem = 1,
                            dataAtualizacao = new DateTime(2021, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dataCriacao = new DateTime(2019, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idClasse = 1,
                            maxMana = 80,
                            maxVida = 100,
                            nomePersonagem = "DeuBug"
                        },
                        new
                        {
                            idPersonagem = 2,
                            dataAtualizacao = new DateTime(2021, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dataCriacao = new DateTime(2016, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idClasse = 4,
                            maxMana = 100,
                            maxVida = 70,
                            nomePersonagem = "BitBug"
                        },
                        new
                        {
                            idPersonagem = 3,
                            dataAtualizacao = new DateTime(2021, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dataCriacao = new DateTime(2018, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idClasse = 7,
                            maxMana = 60,
                            maxVida = 75,
                            nomePersonagem = "Fer7"
                        });
                });

            modelBuilder.Entity("senai.hroads.webAPI.Domains.TipoHabilidadeDomain", b =>
                {
                    b.Property<int>("idTipoHabilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nomeTipoHabilidade")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idTipoHabilidade");

                    b.ToTable("TipoHabilidades");

                    b.HasData(
                        new
                        {
                            idTipoHabilidade = 1,
                            nomeTipoHabilidade = "Ataque"
                        },
                        new
                        {
                            idTipoHabilidade = 2,
                            nomeTipoHabilidade = "Defesa"
                        },
                        new
                        {
                            idTipoHabilidade = 3,
                            nomeTipoHabilidade = "Cura"
                        },
                        new
                        {
                            idTipoHabilidade = 4,
                            nomeTipoHabilidade = "Magia"
                        });
                });

            modelBuilder.Entity("senai.hroads.webAPI.Domains.TipoUsuarioDomain", b =>
                {
                    b.Property<int>("idTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("permissao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idTipoUsuario");

                    b.HasIndex("permissao")
                        .IsUnique();

                    b.ToTable("TipoUsuarios");

                    b.HasData(
                        new
                        {
                            idTipoUsuario = 1,
                            permissao = "ADMINISTRADOR"
                        },
                        new
                        {
                            idTipoUsuario = 2,
                            permissao = "JOGADOR"
                        });
                });

            modelBuilder.Entity("senai.hroads.webAPI.Domains.UsuarioDomain", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<int>("idTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idUsuario");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("idTipoUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            idUsuario = 1,
                            email = "admin@admin.com",
                            idTipoUsuario = 1,
                            senha = "admin"
                        },
                        new
                        {
                            idUsuario = 2,
                            email = "jogador@jogador.com",
                            idTipoUsuario = 2,
                            senha = "jogador"
                        });
                });

            modelBuilder.Entity("senai.hroads.webAPI.Domains.ClasseHabilidadeDomain", b =>
                {
                    b.HasOne("senai.hroads.webAPI.Domains.ClasseDomain", "classe")
                        .WithMany()
                        .HasForeignKey("idClasse");

                    b.HasOne("senai.hroads.webAPI.Domains.HabilidadeDomain", "habilidade")
                        .WithMany()
                        .HasForeignKey("idHabilidade");

                    b.Navigation("classe");

                    b.Navigation("habilidade");
                });

            modelBuilder.Entity("senai.hroads.webAPI.Domains.HabilidadeDomain", b =>
                {
                    b.HasOne("senai.hroads.webAPI.Domains.TipoHabilidadeDomain", "tipoHabilidade")
                        .WithMany()
                        .HasForeignKey("idTipoHabilidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoHabilidade");
                });

            modelBuilder.Entity("senai.hroads.webAPI.Domains.PersonagemDomain", b =>
                {
                    b.HasOne("senai.hroads.webAPI.Domains.UsuarioDomain", null)
                        .WithMany("personagens")
                        .HasForeignKey("UsuarioDomainidUsuario");

                    b.HasOne("senai.hroads.webAPI.Domains.ClasseDomain", "classe")
                        .WithMany()
                        .HasForeignKey("idClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("classe");
                });

            modelBuilder.Entity("senai.hroads.webAPI.Domains.UsuarioDomain", b =>
                {
                    b.HasOne("senai.hroads.webAPI.Domains.TipoUsuarioDomain", "tipoUsuario")
                        .WithMany()
                        .HasForeignKey("idTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoUsuario");
                });

            modelBuilder.Entity("senai.hroads.webAPI.Domains.UsuarioDomain", b =>
                {
                    b.Navigation("personagens");
                });
#pragma warning restore 612, 618
        }
    }
}
